apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    tier: mariadb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
data:
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_DATASOURCE_USERNAME: "spring"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mariadb:3306/spring"
  SPRING_DATASOURCE_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
  SPRING_PROFILES_ACTIVE: "worker"
  DATABASE_ROOT_PASSWORD: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: mariadb
    spec:
      containers:
        - image: mariadb:10.6
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mariadb
                  key: DATABASE_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mariadb
                  key: SPRING_DATABASE_USERNAME
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: mariadb
                  key: SPRING_DATABASE_USERNAME
            - name: MARIADB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mariadb
                  key: SPRING_DATABASE_PASSWORD
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc